---
# Configure access to mysql for app user

- name: set user to app
  command: "echo app"
  register: my_cnf_user

- name: create my.cnf file for app user
  template: src=home/*/my.cnf.j2 dest=/home/app/.my.cnf owner=app group=app mode=600
